
version: "3.8"
services:
  werf:
    image: werf
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1      # AWS_PROFILE=default
      - ENDPOINT_HOST=localstack
      - ENDPOINT_PORT=4566
